<?php
/*
 * View list of topics.
 *
 * DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
 */
include 'header.php';
include 'connect.php';

$_ = $_GET;
$sql = mysqli_connect($connect_url,$connect_user,$connect_password,$connect_database);
if (mysqli_connect_errno($sql))
{
	die("Failed to connect to MySQL: " . mysqli_connect_error());
}
if(isset($_['newpost']))
{
	$newpost = $_['newpost'];
	$q = mysqli_query($sql,'insert into threads (title) values ("' . mysqli_real_escape_string($sql,$newpost) .  '");');
	header('Location: http://' . $_SERVER['HTTP_HOST'] . explode('?',$_SERVER['REQUEST_URI'],2)[0]);
	die();
}

$threads = mysqli_query($sql,"SELECT * FROM threads;");
while($row = mysqli_fetch_array($threads))
	echo '<a href="view.php?id=' . $row['id'] . '"><b>' . $row['title'] . '</b></a><br/>';

?>
<input type="text" id="content"></input>
<button OnClick="window.location.href+='?newpost='+document.getElementById('content').value">Create thread</input>
<?php
include 'footer.php';
?>
